# Generated by Django 4.0 on 2023-03-28 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('competitor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=512)),
                ('price', models.CharField(max_length=512)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('url', models.CharField(max_length=512)),
                ('name', models.CharField(blank=True, max_length=512, null=True)),
                ('image', models.CharField(blank=True, max_length=512, null=True)),
                ('price', models.CharField(blank=True, max_length=512, null=True)),
                ('price_for_month', models.CharField(blank=True, max_length=512, null=True)),
                ('is_available', models.BooleanField(default=True)),
                ('parse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='competitor.competitor')),
            ],
            options={
                'unique_together': {('parse', 'url')},
            },
        ),
        migrations.CreateModel(
            name='ProductPriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('price', models.CharField(blank=True, max_length=512, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='product.product')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
