# Generated by Django 4.0 on 2023-03-30 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitor', '0005_alter_competitorproduct_options_and_more'),
        ('product', '0003_product_delete_mainproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='competitor_products',
            field=models.ManyToManyField(blank=True, to='competitor.CompetitorProduct'),
        ),
    ]
