# Generated by Django 4.0 on 2023-03-31 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitor', '0006_competitor_name'),
        ('product', '0006_product_brand_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='competitor_products',
            field=models.ManyToManyField(blank=True, related_name='main_product', to='competitor.CompetitorProduct'),
        ),
    ]
