# Generated by Django 4.0 on 2023-08-30 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('avtoelon', '0002_alter_auto_body_type_alter_auto_drive_unit_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('link', models.CharField(max_length=512, unique=True)),
                ('is_parsed', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='auto',
            name='link',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='auto', to='avtoelon.autolink'),
            preserve_default=False,
        ),
    ]
