# Generated by Django 4.0 on 2023-03-28 10:11

from django.db import migrations, models
import django.db.models.deletion
import django_better_admin_arrayfield.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Competitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=256, verbose_name='URL-адрес')),
                ('logo', models.CharField(blank=True, editable=False, max_length=512, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='CompetitorUrls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('category', 'Category url'), ('product', 'Product url')], max_length=25)),
                ('url', models.CharField(max_length=512, unique=True)),
                ('parse_site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='urls', to='competitor.competitor')),
            ],
        ),
        migrations.CreateModel(
            name='CompetitorSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sitemaps_urls', django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.CharField(blank=True, max_length=256, null=True), blank=True, null=True, size=None)),
                ('page_pagination_slug', models.CharField(blank=True, max_length=256, null=True)),
                ('category_slug', django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.CharField(blank=True, max_length=256, null=True), blank=True, null=True, size=None)),
                ('product_slug', django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.CharField(blank=True, max_length=256, null=True), blank=True, null=True, size=None)),
                ('competitor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='competitor.competitor')),
            ],
        ),
    ]
