# Generated by Django 4.0 on 2023-03-28 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitor', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='competitor',
            options={'verbose_name': 'Конкурент', 'verbose_name_plural': 'Конкуренты'},
        ),
        migrations.AlterModelOptions(
            name='competitorsetting',
            options={'verbose_name': 'Настройка конкурентов', 'verbose_name_plural': 'Настройки конкурентов'},
        ),
        migrations.RenameField(
            model_name='competitorurls',
            old_name='parse_site',
            new_name='competitor',
        ),
        migrations.AlterField(
            model_name='competitor',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активный мониторинг'),
        ),
    ]
