# Generated by Django 4.0 on 2023-03-30 05:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('competitor', '0003_competitorproduct_alter_competitorurls_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competitorproduct',
            name='image',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='competitorproduct',
            name='is_available',
            field=models.BooleanField(default=True, verbose_name='Доступен '),
        ),
        migrations.AlterField(
            model_name='competitorproduct',
            name='name',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='competitorproduct',
            name='price',
            field=models.IntegerField(default=0, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='competitorproduct',
            name='url',
            field=models.CharField(max_length=512, verbose_name='URL-адрес'),
        ),
        migrations.AlterField(
            model_name='productpricehistory',
            name='price',
            field=models.IntegerField(default=0, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='productpricehistory',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='competitor.competitorproduct', verbose_name='Продукт'),
        ),
    ]
