# Generated by Django 4.0 on 2023-03-30 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competitor', '0004_alter_competitorproduct_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='competitorproduct',
            options={'verbose_name': 'Продукт конкурента', 'verbose_name_plural': 'Продукты конкурентов'},
        ),
        migrations.AlterModelOptions(
            name='productpricehistory',
            options={'verbose_name': 'История цен на товары', 'verbose_name_plural': 'История цен на товары'},
        ),
    ]
