# Generated by Django 4.0 on 2023-03-30 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitor', '0005_alter_competitorproduct_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitor',
            name='name',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
    ]
