# Generated by Django 4.0 on 2023-04-05 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('competitor', '0006_competitor_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competitorsetting',
            name='competitor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='setting', to='competitor.competitor', verbose_name='Конкурент'),
        ),
    ]
