# Generated by Django 4.0 on 2023-04-06 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitor', '0007_alter_competitorsetting_competitor'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitorsetting',
            name='category_parse',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='competitorsetting',
            name='product_parse',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
