# Generated by Django 4.0 on 2023-04-10 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitor', '0008_competitorsetting_category_parse_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='competitor',
            options={'ordering': ['-id'], 'verbose_name': 'Конкурент', 'verbose_name_plural': 'Конкуренты'},
        ),
        migrations.AlterUniqueTogether(
            name='competitorproduct',
            unique_together={('competitor', 'name')},
        ),
        migrations.AlterField(
            model_name='competitor',
            name='logo',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='competitorproduct',
            name='image',
            field=models.URLField(blank=True, max_length=512, null=True, verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='competitorproduct',
            name='is_available',
            field=models.BooleanField(default=True, verbose_name='Доступен'),
        ),
        migrations.AlterField(
            model_name='competitorproduct',
            name='url',
            field=models.URLField(max_length=512, unique=True, verbose_name='URL-адрес'),
        ),
    ]
