# Generated by Django 4.0 on 2023-04-13 06:55

from django.db import migrations
import pgtrigger.compiler
import pgtrigger.migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competitor', '0009_alter_competitor_options_and_more'),
    ]

    operations = [
        pgtrigger.migrations.AddTrigger(
            model_name='competitorproduct',
            trigger=pgtrigger.compiler.Trigger(name='track_price_product_update', sql=pgtrigger.compiler.UpsertTriggerSql(func='\n                    INSERT INTO competitor_productpricehistory(product_id, price)\n                    SELECT\n                        new_values.price AS price,\n                        new_values.id AS product_id\n                    FROM new_values;            \n                    RETURN NULL;', hash='0a34f4391f30dac0c317769646ba4e37ca2bfec3', level='STATEMENT', operation='UPDATE', pgid='pgtrigger_track_price_product_update_07210', referencing='REFERENCING NEW TABLE AS new_values ', table='competitor_competitorproduct', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='competitorproduct',
            trigger=pgtrigger.compiler.Trigger(name='track_price_product_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='\n                    INSERT INTO competitor_productpricehistory(product_id, price)\n                    SELECT\n                        new_values.price AS price,\n                        new_values.id AS product_id\n                    FROM new_values;            \n                    RETURN NULL;', hash='a0f62293ea59752f707f1ad1a6e8db89cc1fd880', level='STATEMENT', operation='INSERT', pgid='pgtrigger_track_price_product_insert_e69e5', referencing='REFERENCING NEW TABLE AS new_values ', table='competitor_competitorproduct', when='AFTER')),
        ),
    ]
