# Generated by Django 4.0 on 2023-04-13 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competitor', '0010_competitorproduct_track_price_product_update_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productpricehistory',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='productpricehistory',
            name='updated_at',
        ),
    ]
